### ISSUE TITLE
SocketManager: Add optional argument pass-through to socketio.AsyncServer constructor

### ISSUE THREAD

**Issue by inactivist** [pyropy/fastapi-socketio#14]
There are times when it may be necessary to be able to pass optional arguments to the [`AsyncServer` constructor.](https://python-socketio.readthedocs.io/en/latest/api.html#socketio.AsyncServer)

The current [`SocketManager` constructor](https://github.com/pyropy/fastapi-socketio/blob/master/fastapi_socketio/socket_manager.py#L28) passes a fixed set of arguments when it initializes the `_sio` instance.

Perhaps an optional dict argument, `socketio_server_args` could be passed down into the `AsyncServer` constructor, as kwargs.

I'll try to work up a PR for this soon.

**Comment by pyropy** [comment]
I added `async_mode` argument that defaults to `asgi`. Take a look at #21 . Sorry because this took this long..
