### ISSUE TITLE
Too many package dependencies

### ISSUE THREAD

**Issue by kristjanvalur** [pyropy/fastapi-socketio#15]
Hi there.
I just noticed when using your module that a lot of modules got pulled in.
In particular, the `netifaces` module is pulled in, which is a binary extension.  And others.
Browsing your code, I can't see that there are other direct dependencies than `fastapi` and `python-socketio`.  But the Pipfile includes a host of extensions, and so does setup.py.   (python-engineio is automatically added as part of python-socketio)
Not sure why the module needs the various "extras" in setup.py, since there is no extras code.

**Comment by pyropy** [comment]
Hey, thanks for addressing the issue. I'll try tidy up the dependencies file in next couple of days 🙏🏻
