### ISSUE TITLE
any way to join rooms?

### ISSUE THREAD

**Issue by ST2-EV** [pyropy/fastapi-socketio#19]
i see that i can emit to specific room but no way to join clients to certain rooms. Any help would be appreciated

**Comment by pyropy** [comment]
@ST2-EV Thanks for reporting this. I've noticed that I've missed to implement that. Sorry for keeping you waiting this long, I'll get onto this asap.

**Comment by pyropy** [comment]
@ST2-EV New version of package is up, let me know if it resolved your issue.

**Comment by ST2-EV** [comment]
Yeah looks good...thanks
