### ISSUE TITLE
Release new version with kwargs parameter support in SocketManager

### ISSUE THREAD

**Issue by rbeeli** [pyropy/fastapi-socketio#41]
Would it be possible to create a new release where the following change is included?

[https://github.com/pyropy/fastapi-socketio/commit/a531f49b30bad6c72e8ee352b8ffd689a90d8fb2](https://github.com/pyropy/fastapi-socketio/commit/a531f49b30bad6c72e8ee352b8ffd689a90d8fb2)

We need this in order to override the `json`-parameter in `AsyncServer` to replace the default Python `json` module used.

**Comment by RaenonX** [comment]
Same feature wanted - this would be a great help
I can try creating a PR if needed @pyropy

**Comment by pyropy** [comment]
Hey folks, I've created new release. Thanks for letting me know.
