### ISSUE TITLE
PIP Installation Result in Empty/Incomplete Module

### ISSUE THREAD

**Issue by tolmanam** [pyropy/fastapi-socketio#5]
The PIP command appears to work:
```
$ pip install fastapi-socketio
Collecting fastapi-socketio
  Downloading fastapi_socketio-0.1-py3-none-any.whl (6.0 kB)
Installing collected packages: fastapi-socketio
Successfully installed fastapi-socketio-0.1
```

But the resulting module is effectively empty:
```
$ find .../site-packages/fastapi_socketio/
.../site-packages/fastapi_socketio/
.../site-packages/fastapi_socketio/__pycache__
.../site-packages/fastapi_socketio/__pycache__/__init__.cpython-38.pyc
.../site-packages/fastapi_socketio/__init__.py
```

The `__init__py` looks like a stub.
```
$ cat .../site-packages/fastapi_socketio/__init__.py 
def example_function():
    return 1 + 1
```

**Comment by pyropy** [comment]
Thank you for reporting the issue, will resolve it soon😁🍀

**Comment by pyropy** [comment]
@tolmanam Thanks for reporting the issue, I resolved it. Turns out I should actually change package version in setup.py also :smile: 

I suck at this stuff :smile: 

Thank you once again for reporting :rocket:

**Comment by tolmanam** [comment]
Great!  Thank you for putting this together and for the quick fix.

**Comment by pyropy** [comment]
@tolmanam No problems, If you have any suggestions for features or feedback feel free to make another issue!
